// Catálogo de insumos/materiais de obra — descrições padronizadas e claras.
// Usado como sugestão (autocomplete) no campo "Material / Descrição" dos pedidos de compra,
// para evitar grafias diferentes do mesmo item. Campo continua de digitação livre.
export const INSUMOS: string[] = [
  // ── Aglomerantes / cimento / cal ──
  "Cimento CP II-F-32 (saco 50kg)",
  "Cimento CP II-E-32 (saco 50kg)",
  "Cimento CP III-40-RS (saco 50kg)",
  "Cimento CP IV-32 (saco 50kg)",
  "Cimento CP V-ARI (saco 50kg)",
  "Cimento branco estrutural (saco 25kg)",
  "Cal hidratada CH-I (saco 20kg)",
  "Cal virgem (saco 20kg)",
  "Gesso em pó comum (saco 40kg)",
  "Gesso cola (saco 25kg)",
  // ── Agregados ──
  "Areia fina lavada (m³)",
  "Areia média lavada (m³)",
  "Areia grossa (m³)",
  "Pedra brita nº 0 (m³)",
  "Pedra brita nº 1 (m³)",
  "Pedra brita nº 2 (m³)",
  "Pedrisco (m³)",
  "Pó de pedra (m³)",
  "Bica corrida / rachão (m³)",
  "Argila expandida (m³)",
  // ── Concreto / argamassas industrializadas ──
  "Concreto usinado FCK 20 MPa (m³)",
  "Concreto usinado FCK 25 MPa (m³)",
  "Concreto usinado FCK 30 MPa (m³)",
  "Concreto usinado bombeado FCK 30 MPa (m³)",
  "Argamassa colante AC-I interno (saco 20kg)",
  "Argamassa colante AC-II (saco 20kg)",
  "Argamassa colante AC-III porcelanato (saco 20kg)",
  "Argamassa de assentamento/reboco pronta (saco 20kg)",
  "Argamassa polimérica impermeabilizante (kit)",
  "Rejunte acrílico (saco 1kg)",
  "Rejunte epóxi (kit 1kg)",
  "Aditivo plastificante para concreto (galão 18L)",
  "Aditivo impermeabilizante para argamassa (galão 18L)",
  // ── Alvenaria ──
  "Tijolo cerâmico furado 9x14x19 cm (un)",
  "Tijolo cerâmico furado 9x19x19 cm (un)",
  "Tijolo cerâmico furado 14x19x29 cm (un)",
  "Tijolo maciço cerâmico (un)",
  "Bloco de concreto estrutural 14x19x39 cm (un)",
  "Bloco de concreto estrutural 19x19x39 cm (un)",
  "Bloco de concreto vedação 9x19x39 cm (un)",
  "Bloco cerâmico estrutural 14x19x29 cm (un)",
  "Canaleta de concreto 14x19x39 cm (un)",
  "Verga/contraverga pré-moldada (un)",
  // ── Aço / ferragens ──
  "Aço CA-50 Ø 5,0 mm (barra 12m)",
  "Aço CA-50 Ø 6,3 mm (barra 12m)",
  "Aço CA-50 Ø 8,0 mm (barra 12m)",
  "Aço CA-50 Ø 10,0 mm (barra 12m)",
  "Aço CA-50 Ø 12,5 mm (barra 12m)",
  "Aço CA-50 Ø 16,0 mm (barra 12m)",
  "Aço CA-60 Ø 4,2 mm (barra 12m)",
  "Aço CA-60 Ø 5,0 mm (barra 12m)",
  "Tela soldada nervurada Q-138 (painel)",
  "Tela soldada nervurada Q-196 (painel)",
  "Arame recozido nº 18 (kg)",
  "Arame galvanizado (kg)",
  "Prego 17x27 com cabeça (kg)",
  "Prego 18x30 (kg)",
  "Prego 19x36 (kg)",
  "Espaçador de plástico para ferragem (un)",
  // ── Madeira / fôrmas ──
  "Chapa de madeira compensada plastificada 18mm (un)",
  "Chapa de madeira compensada resinada 14mm (un)",
  "Sarrafo de pinus 2,5x7 cm (un)",
  "Caibro 5x6 cm (un)",
  "Pontalete de eucalipto 3m (un)",
  "Tábua de pinus 2,5x30 cm (un)",
  "Ripão de madeira (un)",
  "Desmoldante para fôrma (galão 18L)",
  // ── Gesso / drywall / forro ──
  "Placa de gesso acartonado standard 12,5mm (un)",
  "Placa de gesso acartonado RU (verde) 12,5mm (un)",
  "Placa cimentícia 10mm (un)",
  "Montante drywall 48mm (barra 3m)",
  "Guia drywall 48mm (barra 3m)",
  "Massa para drywall (saco 20kg)",
  "Fita de papel para junta drywall (rolo)",
  "Placa de forro de gesso 60x60 cm (un)",
  "Forro de PVC réguas (m²)",
  "Lã de PET para isolamento (m²)",
  // ── Revestimentos ──
  "Porcelanato esmaltado 60x60 cm (m²)",
  "Porcelanato acetinado 80x80 cm (m²)",
  "Piso cerâmico 45x45 cm (m²)",
  "Azulejo cerâmico 30x60 cm (m²)",
  "Revestimento de fachada / pastilha (m²)",
  "Rodapé de porcelanato 7cm (m)",
  "Soleira de granito (m)",
  "Peitoril de granito (m)",
  "Granito para bancada (m²)",
  // ── Impermeabilização ──
  "Manta asfáltica 3mm (rolo 10m²)",
  "Manta líquida acrílica (balde 18L)",
  "Veda calha / asfalto elástico (galão 3,6L)",
  "Tinta betuminosa (galão 18L)",
  "Hidrofugante de superfície (galão 5L)",
  // ── Tintas / pintura ──
  "Tinta acrílica fosca interna (lata 18L)",
  "Tinta acrílica premium externa (lata 18L)",
  "Tinta látex PVA (lata 18L)",
  "Massa corrida PVA (balde 25kg)",
  "Massa acrílica (balde 25kg)",
  "Selador acrílico (lata 18L)",
  "Fundo preparador de parede (galão 3,6L)",
  "Textura acrílica (balde 25kg)",
  "Esmalte sintético (galão 3,6L)",
  "Verniz para madeira (galão 3,6L)",
  "Rolo de lã 23cm (un)",
  "Pincel/trincha 2'' (un)",
  "Fita crepe 48mm (rolo)",
  "Lixa para parede grão 120 (un)",
  // ── Hidráulica ──
  "Tubo PVC esgoto 40mm (barra 6m)",
  "Tubo PVC esgoto 50mm (barra 6m)",
  "Tubo PVC esgoto 100mm (barra 6m)",
  "Tubo PVC soldável água fria 25mm (barra 6m)",
  "Tubo PVC soldável água fria 32mm (barra 6m)",
  "Tubo PPR água quente 25mm (barra)",
  "Joelho 90° PVC soldável 25mm (un)",
  "Tê PVC soldável 25mm (un)",
  "Luva PVC soldável 25mm (un)",
  "Joelho 90° esgoto 100mm (un)",
  "Curva 90° esgoto 100mm (un)",
  "Caixa sifonada 100x100x50 (un)",
  "Ralo seco/grelha (un)",
  "Registro de gaveta 3/4'' bruto (un)",
  "Registro de pressão 3/4'' bruto (un)",
  "Adesivo plástico PVC (bisnaga 175g)",
  "Fita veda-rosca 18mmx50m (rolo)",
  "Caixa d'água polietileno 1000L (un)",
  "Tubo PVC água pluvial 100mm (barra 6m)",
  // ── Elétrica ──
  "Eletroduto PVC corrugado 3/4'' (rolo 50m)",
  "Eletroduto rígido PVC 3/4'' (barra 3m)",
  "Cabo flexível 1,5mm² (rolo 100m)",
  "Cabo flexível 2,5mm² (rolo 100m)",
  "Cabo flexível 4,0mm² (rolo 100m)",
  "Cabo flexível 6,0mm² (rolo 100m)",
  "Cabo flexível 10mm² (m)",
  "Disjuntor monopolar 16A (un)",
  "Disjuntor monopolar 20A (un)",
  "Disjuntor bipolar 25A (un)",
  "Disjuntor DR 40A (un)",
  "DPS classe II (un)",
  "Quadro de distribuição 12/18 disjuntores (un)",
  "Caixa de luz 4x2'' PVC (un)",
  "Caixa de luz 4x4'' PVC (un)",
  "Tomada 2P+T 10A com placa (un)",
  "Tomada 2P+T 20A com placa (un)",
  "Interruptor simples com placa (un)",
  "Interruptor paralelo com placa (un)",
  "Fita isolante 19mmx20m (un)",
  "Abraçadeira/braçadeira nylon (pacote)",
  // ── Cobertura / esquadrias / vidros ──
  "Telha cerâmica portuguesa (un)",
  "Telha de fibrocimento 6mm (un)",
  "Telha metálica termoacústica (m²)",
  "Calha galvanizada (m)",
  "Rufo/pingadeira galvanizado (m)",
  "Porta de madeira semi-oca 80x210 com batente (un)",
  "Porta de madeira semi-oca 70x210 com batente (un)",
  "Kit porta pronta 80cm (un)",
  "Janela de alumínio de correr 1,20x1,00m (un)",
  "Fechadura de embutir externa (un)",
  "Dobradiça 3'' (par)",
  "Vidro temperado 8mm (m²)",
  "Vidro comum 4mm (m²)",
  // ── Louças e metais ──
  "Bacia sanitária com caixa acoplada (un)",
  "Cuba de embutir para banheiro (un)",
  "Cuba de inox para cozinha (un)",
  "Torneira de lavatório (un)",
  "Torneira de cozinha de parede (un)",
  "Misturador monocomando (un)",
  "Chuveiro/ducha (un)",
  "Sifão sanfonado (un)",
  "Engate flexível 40cm (un)",
  "Válvula de escoamento (un)",
  // ── EPI / consumíveis / canteiro ──
  "Capacete de segurança (un)",
  "Luva de raspa (par)",
  "Luva nitrílica (par)",
  "Óculos de proteção (un)",
  "Bota de segurança (par)",
  "Protetor auricular (par)",
  "Cinto de segurança paraquedista (un)",
  "Disco de corte 7'' (un)",
  "Disco diamantado 110mm (un)",
  "Broca de widia 10mm (un)",
  "Lona plástica preta (m²)",
  "Tela de proteção de fachada (m²)",
  "Saco para entulho (un)",
  "Carrinho de mão (un)",
  "Balde plástico 20L (un)",
  "Desempenadeira de aço (un)",
  "Colher de pedreiro (un)",
  "Linha de pedreiro (rolo)",
  "Mangueira de nível (m)",
];
